services:
  app:
    image: app
    build: .
    env_file: ./.env
    container_name: app
    hostname: app
    command: ['bundle', 'exec', 'ruby', 'run.rb', '--headless', '--bot']
    # command: tail -f /dev/null
    volumes:
      - gems:/usr/local/bundle
    networks:
      - net
    restart: always

volumes:
  gems:

networks:
  net: